/*
 * File: Data.Grid.ui.js
 * Date: Sat Jun 04 2011 17:20:43 GMT-0300 (Hora oficial do Brasil)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('Data');
Data.GridUi = Ext.extend(Ext.grid.GridPanel, {
    title: 'Dados',
    store: 'disastersStore',
    initComponent: function() {
        this.columns = [
            {
                xtype: 'gridcolumn',
                dataIndex: 'string',
                header: 'Município',
                sortable: true,
                width: 100
            },
            {
                xtype: 'numbercolumn',
                dataIndex: 'number',
                header: 'Evento',
                sortable: true,
                width: 100,
                align: 'right'
            },
            {
                xtype: 'datecolumn',
                dataIndex: 'date',
                header: 'Data',
                sortable: true,
                width: 100
            },
            {
                xtype: 'booleancolumn',
                dataIndex: 'bool',
                header: 'Desalojados',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'Desabrigados',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'Mortos',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'Afetados',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'Res. Destruidas',
                sortable: true,
                width: 100
            },
            {
                xtype: 'gridcolumn',
                header: 'Res. Danificadas',
                sortable: true,
                width: 100
            }
        ];
        Data.GridUi.superclass.initComponent.call(this);
    }
});
