/*
 * File: DataType.Store.js
 * Date: Sat Jun 04 2011 17:20:43 GMT-0300 (Hora oficial do Brasil)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('DataType');
DataType.Store = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        DataType.Store.superclass.constructor.call(this, Ext.apply({
            storeId: 'dataTypeStore',
            data: [
                   {id:'desalojados',name:'Desalojados'},
                   {id:'desabrigados',name:'Desabrigados'},
                   {id:'mortos',name:'Mortos'},
                   {id:'atingidos',name:'Atingidos'},
                   {id:'res_destruidas',name:'Residências Danificadas'},
                   {id:'res_danificadas',name:'Residências Destruidas'}
            ],
            fields: [
                {
                    name: 'name',
                    name:'id'
                }
            ]
        }, cfg));
    }
});
new DataType.Store();