/*
 * File: Disaster.Store.js
 * Date: Sat Jun 04 2011 14:56:12 GMT-0300 (Hora oficial do Brasil)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('Disaster');
Disaster.Store = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        Disaster.Store.superclass.constructor.call(this, Ext.apply({
            storeId: 'disastersStore',
            fields: [
                { name: 'codigoIBGE' },
                { name: 'municipio' },
                { name: 'eventoCodar' },
                { name: 'entrada' },
                { name: 'desalojados' },
                { name: 'desabrigados' },
                { name: 'mortos' },
                { name: 'afetados' },
                { name: 'residenciasDanificadas' },
                { name: 'residenciasDestruidas' },
                { name: 'dataOcorrencia' },
                { name: 'dataTermino' }
            ],
        	data	: [
        	   {municipio:'floripa', eventoCodar:'a', dataOcorrencia:'12/12/12', desalojados:10, desabrigados:10, mortos:12, afetados:10, residenciasDestruidas:8, residenciasDanificadas:20}
        	   ,{municipio:'floripa', eventoCodar:'b', dataOcorrencia:'12/10/12', desalojados:20, desabrigados:15, mortos:7, afetados:11, residenciasDestruidas:10, residenciasDanificadas:12}
        	   ,{municipio:'floripa', eventoCodar:'c', dataOcorrencia:'12/11/12', desalojados:15, desabrigados:12, mortos:11, afetados:15, residenciasDestruidas:15, residenciasDanificadas:12}
        	]
        }, cfg));
    }
});
Ext.reg('disasterstore', Disaster.Store);new Disaster.Store();