/*
 * File: Filter.Panel.ui.js
 * Date: Sat Jun 04 2011 17:20:43 GMT-0300 (Hora oficial do Brasil)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('Filter');
Filter.PanelUi = Ext.extend(Ext.Panel, {
    height: 175,
    layout: 'form',
    baseCls: 'x-plain',
    padding: 5,
    initComponent: function() {
        this.items = [
            {
                xtype: 'combo',
                fieldLabel: 'Tipo de desastre',
                anchor: '100%',
                store: 'disasterTypeStore',
                ref: 'disasterTypeCombo'
            },
            {
                xtype: 'combo',
                fieldLabel: 'Estado',
                ref: '../stateField',
                anchor: '100%',
                store: 'statesStore',
                ref: 'stateCombo'
            },
            {
                xtype: 'combo',
                fieldLabel: 'Município',
                anchor: '100%',
                store: 'citiesStore',
                ref: 'stateCombo'
            },
            {
                xtype: 'combo',
                fieldLabel: 'Ano',
                store: 'yearsStore',
                ref:'../yearField',
                valueField: 'year',
                displayField: 'year',
                mode: 'local',
                triggerAction: 'all'
            },
            {
                xtype: 'combo',
                fieldLabel: 'Dado',
                store: 'disasterTypeStore',
                ref: '../typeField',   
                hiddenName: 'disasterType',
                valueField: 'pqp',
                displayField: 'name',
                mode: 'local',
                triggerAction: 'all'                    	
            },
            {
                xtype: 'button',
                text: 'Gerar',
                ref: '../generateButton'
            }
        ];
        Filter.PanelUi.superclass.initComponent.call(this);
    }
});
