/*
 * File: Main.Window.js
 * Date: Sat Jun 04 2011 14:20:56 GMT-0300 (Hora oficial do Brasil)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

Main.Window = Ext.extend(Main.WindowUi, {
    initComponent: function() {
        Main.Window.superclass.initComponent.call(this);
        
        this.generateButton.on('click', this.onGenerate, this);
    }

	,onGenerate : function() {
		var year = this.yearField.getValue();
		var type = this.typeField.getValue();
		//var state = this.stateField.getValue();
		var state = '';
		
		/*
		this.chart.store.reload({
			params : {
				year : year,
				//type : type,
				state : state
			}
		}); */
		
		switch(type) {
		
	        case 'atinjidos':
	        	this.chartsPanel.getLayout().setActiveItem(0);
				break;				
				
	        case 'desabrigados':
	        	this.chartsPanel.getLayout().setActiveItem(1);
		
			case 'desalojados':
				this.chartsPanel.getLayout().setActiveItem(2);
				break;
				
	        case 'mortos':
	        	this.chartsPanel.getLayout().setActiveItem(3);
				break;
				
	        case 'res_danificadas':
	        	this.chartsPanel.getLayout().setActiveItem(4);
				break;
				
	        case 'res_destruidas':
	        	this.chartsPanel.getLayout().setActiveItem(5);
				break;			
		}
		
	}
});
