/*
 * File: Main.Window.ui.js
 * Date: Sat Jun 04 2011 17:20:43 GMT-0300 (Hora oficial do Brasil)
 * 
 * This file was generated by Ext Designer version 1.1.2.
 * http://www.sencha.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.ns('Main');
Main.WindowUi = Ext.extend(Ext.Window, {
    title: 'Anuário Brasileiro de Desastres',
    width: 771,
    height: 600,
    layout: 'border',
    initComponent: function() {
        this.items = [
            {
                region: 'north',
                ref: 'filterpanel',
                xtype: 'filterpanel'
            },
            {
                xtype: 'panel',
                ref:'chartsPanel',
                layout:'card',
                activeItem: 0,
                region: 'center',
                items: [
                    {
                        xtype: 'afetadoschart'
                    },
                    {
                        xtype: 'desabrigadoschart'
                    },
                    {
                        xtype: 'desalojadoschart'
                    },
                    {
                        xtype: 'mortoschart'
                    },
                    {
                        xtype: 'residenciasdanificadaschart'
                    },
                    {
                        xtype: 'residenciasdestruidaschart'
                    }
                ]
            }
        ];
        Main.WindowUi.superclass.initComponent.call(this);
    }
});
